#############################################################################
# Makefile for building: pMiniSat
# Generated by qmake (3.0) (Qt 5.7.0)
# Template: app
#############################################################################

MAKEFILE      = Makefile

####### Compiler and options

CXX           = g++
CXXFLAGS      = -ltbb -pthread -std=c++11 -O3
#CXXFLAGS      = -ltbb -pthread -std=gnu++11 -g -O0
INCPATH       = -Isrc/ 
DEL_FILE      = rm -f
LINK          = g++
#LFLAGS        =  -pthread -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro -ltbb
LFLAGS        =  -pthread -O1 -ltbb

####### Files
OBJECTS       = Cooperation.o \
                Solver.o \
                main.o \
                Dimacs.o \
		Clause.o \
		VarOrder.o\
		propagateunit.o
TARGET        = pMiniSat


first: all
####### Build rules

all: $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS) $(LFLAGS)

clean: 
	-$(DEL_FILE) $(OBJECTS) $(TARGET)

main.o: src/main.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

Clause.o: src/Clause.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Clause.o src/Clause.cpp

Solver.o: src/Solver.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Solver.o src/Solver.cpp

VarOrder.o: src/VarOrder.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VarOrder.o src/VarOrder.cpp

Dimacs.o: src/Dimacs.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Dimacs.o src/Dimacs.cpp

Cooperation.o: src/Cooperation.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cooperation.o src/Cooperation.cpp
propagateunit.o: src/propagateunit.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o propagateunit.o src/propagateunit.cpp

